### PR TITLE
Update to Laravel 11

### PR DESCRIPTION
**Pull request by kaptk2**

### CODE REVIEW

**Review by andreia — COMMENTED** [review]
Can we keep `"illuminate/contracts"` instead of `"laravel/framework"`?

**Comment by kaptk2** [comment]
No, that package conflicts with Laravel 11, either `laravel/framework` or` illuminate/contracts` can be installed but not both.

**Comment by andreia** [comment]
> No, that package conflicts with Laravel 11, either `laravel/framework` or` illuminate/contracts` can be installed but not both.

@kaptk2 Thank you for your prompt reply! :)
I apologize for being unclear, what I meant was using `illuminate/contracts` instead of `laravel/framework`

**Comment by kaptk2** [comment]
Oh, yes. I see what you mean. I made the change and everything still works as it should

**Review by andreia — APPROVED** [review]
@kaptk2 Thank you!

**Pull request merged**
